{% set name = "simple-binary-encoding" %}
{% set version = "1.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/real-logic/simple-binary-encoding/archive/refs/tags/{{ version }}.tar.gz
  sha256: 341ff69eb684242597139380d17cf400d4618d68b6cf0ce732e2b60b919a1d3d
  patches:
    - license-report.patch

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: sbe-java
    script: build-java.sh
    requirements:
      build:
        - gradle
      host:
      run:
    test:
      commands:
        - test -f ${PREFIX}/lib/sbe-all-{{ version }}.jar  # [unix]

  - name: sbe-cxx
    script: build-cxx.sh  # [unix]
    script: bld-cxx.bat  # [win]
    requirements:
      build:
        - gradle
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - openjdk
        - {{ pin_subpackage("sbe-java", exact=True) }}
      run:
    test:
      commands:
        - test -f ${PREFIX}/include/otf/Encoding.h  # [unix]
        - test -f ${PREFIX}/include/otf/IrDecoder.h  # [unix]
        - test -f ${PREFIX}/include/otf/OtfHeaderDecoder.h  # [unix]
        - test -f ${PREFIX}/include/otf/OtfMessageDecoder.h  # [unix]
        - test -f ${PREFIX}/include/otf/Token.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/ByteOrderCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/FrameCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/MessageHeader.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/PresenceCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/PrimitiveTypeCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/SignalCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/TokenCodec.h  # [unix]
        - test -f ${PREFIX}/include/otf/uk_co_real_logic_sbe_ir_generated/VarDataEncoding.h  # [unix]


about:
  home: https://github.com/real-logic/simple-binary-encoding
  summary: 'SBE is an OSI layer 6 presentation for encoding and decoding binary application messages for low-latency financial applications'
  description: |
    SBE is an OSI layer 6 presentation for encoding and decoding binary application messages for
    low-latency financial applications. This repository contains the reference implementations
    in Java, C++, Golang, C#, and Rust.
  license: Apache-2.0 AND MIT AND GPL-2.0-only WITH Classpath-exception-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  doc_url: https://github.com/real-logic/simple-binary-encoding/wiki
  dev_url: https://github.com/real-logic/simple-binary-encoding

extra:
  feedstock-name: "simple-binary-encoding"
  recipe-maintainers:
    - zklaus
    - timkpaine
